### ISSUE TITLE
Create actions

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [VibhorCodecianGupta/Bulls-and-Bears#19]
It's time to add the real meat to the routes. Create the action functions for all the routes. This is to be done after #18 gets merged.

Use [this doc](https://docs.google.com/spreadsheets/d/1QMHvDYByolWRA9CAzpZmlcQ57A2Ba1uddQBy1BFVDeg/edit#gid=0) for reference

**Comment by shivanggarg1998** [comment]
I am working on it
