### ISSUE TITLE
Google login

### ISSUE THREAD

**Issue by VibhorCodecianGupta** [VibhorCodecianGupta/Bulls-and-Bears#23]
Required a google login functionality just like there is one for Facebook. Take care of authentication, authorization, and also check for duplicate logins (a user shouldn't be able to connect with both google and facebook. If he/she tries, return the already existing account of that user)

**Comment by zephyr007** [comment]
made the authentication with google. but it will take some time o make a check function for both login`s

**Comment by zephyr007** [comment]
we can check for email by for all facebook users and all google users  ,Check for same mail id n eliminating users.but i couldn`t find out mongooseDb function for adding users. we can aaply that funcion there

**Comment by VibhorCodecianGupta** [comment]
Done for now, will reopen if required
